service: serverless-nestjs

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'sns:*'
          Resource:
            - '*'

plugins:
  - serverless-offline

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - e2e/**
    - nodemon.json
    - README.md

functions:
  main:
    handler: dist/index.handler
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: true
